### ISSUE TITLE
Back | Task | FFT analysis

### ISSUE THREAD

**Issue by a-givertzman** [a-givertzman/cma-server#133]
# FFT analysis for the Task service

- [x] Do the FFT on the sequence #129 
- [x] Configurable frequence range and step #129 
- [ ] Configurable threshold filtering
- [ ] Storing into the DB
- [ ] Configurable 'FFT' filtering - removes periodic components  - #130
- [ ] Configurable 'Trend' filtering - removing the noise (white noise)
