### ISSUE TITLE
Back | CMA-Recorder

### ISSUE THREAD

**Issue by a-givertzman** [a-givertzman/cma-server#91]
#### CMA-Recorder
Based on the CMA-Server Task

- [x] Operating cycle
  - table: 'operating_cycle'
  - [x] Detect operating cycle begins
  - [x] Detect operating cycle ends
    - [x] Store operating cycle record 
      - begins timestamp
      - ends timestamp
      - metrics
- [x] Basic metrics, see #103 for details
  - based on the ГОСТ 34017-2016
  - table: 'rec_basic_metric'
- [x] Operating cycle 
  - table: 'rec_operating_cycle'
- [x] Operating cycle metrics 
  - table: 'rec_operating_metric'
- [x] Live Data 
  - table: 'rec_operating_event'
---
#### Classes
- [x] #92 
- [x] FnDetectOpCycle
   - nom             - The nominal value of the crane load
   - threshold     - Triggering threshold of the operating cycle detection function on the input value based on the nominal value
   - input            - input value
Temporary solved using the fallowing conf
```yaml
    #
    # The nominal load of the crane
    let craneLoadNom:
        input: point real '/AppTest/Load.Nom'
    #
    # 5 % of the nominal crane load - used for Op Cycle detection
    let opCycleThreshold:
        input fn Mul:
            input1: const real 0.05
            input2: craneLoadNom
    #
    # Detect if operating cycle is active (true - isActive, false - isNotActive)
    let opCycleIsActive:
        input fn Export:
            send-to: /AppTest/TaskTestReceiver.in-queue
            conf point OpCycle:
                type: 'Bool'
            input fn Ge:
                input2: opCycleThreshold
                input1 fn Threshold:                 # Triggering threshold of the operating cycle detection function on the input value based on the nominal value
                    threshold: opCycleThreshold
                    input fn Smooth:
                        factor: const real 0.125
                        input: point real '/AppTest/Load'
```
- [x] Retain - Stores current value on input to the local cache with the given name #97 
   - name 
   - input
- [x] FnExport - sends current value from input if condition is true #94 
   - send-to
   - condition
   - input
- [x] FnAcc - Task function accumulate input Point's value, returns accumulated value #96 
   - initial - function starts from this value
   - input - incoming points
- [x] FnThreshold - kind of simple filtering #98 
  Returns filtered input:
  - if factor is not specified:
     - new input value returned if |prev - [input]| >= [threshold]
  - if factor is specified:
     - each cycle: delta += |(prev - [input]) * factor|
     - new input value returned if delta >= [threshold]
- [x] FnSmooth - kind of simple filtering #99 
  Returns smoothed input:
  `out = out + (input - prev) * factor`
- [x] Task | FnMul #100 
- [x] Task | FnSub #101
- [x] Task | FnDiv #102
- [x] Task | PiecewiseLineApprox (кусочно-линейная аппроксимация) #107 
- [x] Task | Comparison functions #109
- [x] Task | Bitwise Boolean functions #111
- [x] Task | Input different options #119
